#!/usr/bin/env python3
"""Vendor the three pinned Bank 00 map sources into this repository.

This tool intentionally copies *source code only*. No ROM/base-ROM input is read.
The git submodule SHAs are pinned in the superproject, so the resulting files are
reproducible from the repository checkout.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

VARIANTS = {
    "western": ROOT / "reference" / "pokegold" / "home" / "map.asm",
    "japanese": ROOT / "reference" / "pokesilver" / "home" / "map.asm",
    "korean": ROOT / "reference" / "pokegold-kr" / "home" / "map.asm",
}

OUT_DIR = ROOT / "home" / "map_variants"
WRAPPER = ROOT / "home" / "map.asm"

PROVENANCE = {
    "western": "pret/pokegold @ 656583c939d30f920a316177311a502dd222b57c",
    "japanese": "Narishma-gb/pokesilver @ edbe53978ef1777fc5c41019e17b7544070eab92",
    "korean": "Narishma-gb/pokegold-kr @ f4496dda3003ccc5fc26f2757171a3b111e65307",
}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, src in VARIANTS.items():
        if not src.is_file():
            raise SystemExit(f"missing pinned source: {src}; initialize submodules first")
        body = src.read_text(encoding="utf-8")
        header = (
            "; Vendored Bank 00 map source.\n"
            f"; Provenance: {PROVENANCE[name]}\n"
            "; Generated by tools/vendor_map_source.py; edit the upstream merge layer, not this copy.\n\n"
        )
        (OUT_DIR / f"{name}.asm").write_text(header + body, encoding="utf-8")

    WRAPPER.write_text(
        "; Self-contained Bank 00 map source selector.\n"
        "; Variant files are exact source snapshots generated from the pinned references.\n"
        "; A later deduplication pass will collapse common code to narrow region conditionals.\n\n"
        "IF DEF(_JAPANESE)\n"
        "\tINCLUDE \"home/map_variants/japanese.asm\"\n"
        "ELIF DEF(_KOREAN)\n"
        "\tINCLUDE \"home/map_variants/korean.asm\"\n"
        "ELSE\n"
        "\tINCLUDE \"home/map_variants/western.asm\"\n"
        "ENDC\n",
        encoding="utf-8",
    )

    print("Vendored Bank 00 map sources:")
    for name in VARIANTS:
        path = OUT_DIR / f"{name}.asm"
        print(f"  {name:8s} {path.relative_to(ROOT)} {path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
